# Generated by Django 5.0.3 on 2024-04-02 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_alter_parent_children'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fisrt_name',
            new_name='first_name',
        ),
    ]
