# Generated by Django 5.0.3 on 2024-04-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('core_app', '0003_rename_fisrt_name_student_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together={('grade', 'section', 'subject', 'teacher')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('grade', 'section')},
        ),
    ]
