# Generated by Django 5.0.3 on 2024-04-10 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_grade_grade_alter_classsubject_unique_together_and_more'),
        ('academics', '0002_exam'),
    ]

    operations = [
    ]
