# Generated by Django 5.0.3 on 2024-04-11 13:49

import django.db.models.deletion
import teacher.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('core_app', '0003_rename_fisrt_name_student_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('exam_date', models.DateField()),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.classsubject')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.grade')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='', validators=[teacher.models.validate_exam_result])),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.exam')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='resource/pdf/', validators=[teacher.models.validate_file_pdf])),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.grade')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('type', models.CharField(choices=[('homework', 'Homework'), ('assignment', 'Assignment')], max_length=20)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.classsubject')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
