# Generated by Django 5.0.3 on 2024-04-10 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_merge_20240410_0659'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresult',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='total_marks',
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('exam_date', models.DateField()),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.classsubject')),
            ],
        ),
        migrations.AlterField(
            model_name='examresult',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.exam'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('type', models.CharField(choices=[('homework', 'Homework'), ('assignment', 'Assignment')], max_length=20)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.classsubject')),
            ],
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
