# Generated by Django 5.0.3 on 2024-04-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_task_title_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='content_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
