# Generated by Django 5.0.3 on 2024-04-10 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_merge_20240410_0659'),
        ('teacher', '0004_resource_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.grade'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.subject'),
        ),
    ]
