# Generated by Django 5.0.3 on 2024-04-10 23:08

import teacher.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_alter_resource_grade_alter_resource_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='content_type',
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(upload_to='resource/pdf/', validators=[teacher.models.validate_file_pdf]),
        ),
    ]
